### PR TITLE
Initial OSLC Configuration Management PSD01 draft

### PR DESCRIPTION
**Pull request by ndjc**
Just a draft PR for now

### CODE REVIEW

**Comment by ndjc** [comment]
fixes #193

**Comment by berezovskyi** [comment]
please merge master into your branch, I won't touch it given it's a draft

**Comment by berezovskyi** [comment]
@ndjc I suggest you use the same approach I used in #481 and merge this PR with a WD status (without going for a PSD) so that we can actually open an HTML rendering of the spec during the OP call next week.

**Comment by berezovskyi** [comment]
should we close this PR without merging given that we just merged #494?

**Comment by berezovskyi** [comment]
@jamsden should we close this PR without merging in favour of https://github.com/oslc-op/oslc-specs/pull/532?

**Comment by berezovskyi** [comment]
Not planning to merge, changes were merged into Jim's Config branch.

**Pull request closed without merging**
