### PR TITLE
Add CORS reference

### PR DESCRIPTION
**Pull request by berezovskyi**
See #458

### CODE REVIEW

**Review by ndjc — CHANGES_REQUESTED** [review]
The reference to CORS uses a specific commit - but if you view that URI in a browser, if gives this warning:

> This document contains the contents of the standard as of the d070ea245c6eb66cf4196324f063dc6ab608d9e6 commit, and should only be used as a historical reference.
> Do not attempt to implement this version of the standard. Do not reference this version as authoritative in any way. Instead, see https://fetch.spec.whatwg.org/ for the living standard.

Should we not follow those instructions?

**Comment by berezovskyi** [comment]
I don't think we should follow those instructions, we are linking to that page exactly for historical reference. The person who clicks on that link will see that warning and will click the "latest" link to see the "living standard" version (whatever that means). If there is no CORS section anymore in that document 10 years from now, at least they have my snapshot link to go back to. WHATWG and W3C had a disagreement (to put it mildly) over WHATWG refusal to version their specs but I side with W3C that snapshots have to be versioned once in a while to provide a stable frame of reference.

**Review by jamsden — CHANGES_REQUESTED** [review]
This is fine in the standard. But a technical note would tell client and server developers what that actually means in practice. That can of course come later, but would be valuable.

make CORS reference normative [[!CORS]]

**Comment by berezovskyi** [comment]
@jamsden, thank you! I made the reference normative and also added two extra SHOULDs on the specific headers. I believe no further guidance is needed beyond reading https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Review by ndjc — APPROVED** [review]

**Comment by berezovskyi** [comment]
Snapshot of a snapshot to be really sure: https://web.archive.org/web/20210128153906/https://fetch.spec.whatwg.org/commit-snapshots/d070ea245c6eb66cf4196324f063dc6ab608d9e6/

**Pull request merged**
