### PR TITLE
Updated vocab and shapes and added multi-valued property ordering

### PR DESCRIPTION
**Pull request by jamsden**
Vocab and shapes use OMG namespaces except: 1) use http instead of https, 2) the vocab namespace is not versioned.

Properties that appear in more than one class no longer have class prefixes in the vocab or shape files.

Properties that appear in more than one class have  their descriptions concatenated in one rdfs:comment.

ShapeChecker mostly validates the vocab and shapes. There are still some issues to resolve.

Updates to ShapeChecker are included to work around the issue that purl.org is not accessible so DCTERMS and vann can't be resolved.

### CODE REVIEW

**Comment by jamsden** [comment]
ShapeChecker gets one error:
```
Checked shapes from file:/Users/jamsden/Developer/oslc-specs/tools/ShapeChecker/../../specs/sysml/sysml-shapes.ttl, with 16 issues (0 info, 15 warnings, 1 errors)
   While examining resource shape http://www.omg.org/spec/SysML/shapes/20240801#OwningMembershipShape:
      While examining property definition ownedMemberShortName:
         Error on http://www.w3.org/2001/XMLSchema#string: The target resource cannot be fetched or parsed as RDF. (bad value org.apache.jena.riot.RiotException: Failed to determine the content type: (URI=http://www.w3.org/2001/XMLSchema : stream=text/plain))
```
I can't see anything wrong with this.

**Comment by jamsden** [comment]
ShapeChecker will hang until the above changes are deployed.

**Comment by jamsden** [comment]
@berezovskyi I asked you to review because of the ShapeChecker updates, and to ensure the vocab and shapes look right to you.

**Review by berezovskyi — APPROVED** [review]
Looks good. For such a large set of shapes, would be good to have some small test suite using https://github.com/eclipse-lyo/lyo/tree/master/validation and to validate some test data and be sure it passes/fails validation as expected.

On my side, I see all checks pass.

**Pull request merged**
