### PR TITLE
Jra trs v3.0 psd01

### PR DESCRIPTION
**Pull request by jamsden**
Editorial changes to publish TRS v3.0 PSD01.

### CODE REVIEW

**Comment by berezovskyi** [comment]
Looks good, let's proceed to notify the PGB!

**Comment by ndjc** [comment]
Don't these changes remove many of the changes I made to address feedback from Andrew?

**Comment by jamsden** [comment]
Not sure what the status of those changes are or where they are.

**Comment by berezovskyi** [comment]
Thanks Nick! What are we going to do without you :)

My last comment was about the last two commits, and Nick is right.

Jim, the status of those changes is merged and they are already on master! Your PR is undoing them, unwittingly so, I believe.

**Comment by berezovskyi** [comment]
@jamsden should we close this PR without merging in favour of https://github.com/oslc-op/oslc-specs/pull/530?

**Pull request closed without merging**
