### PR TITLE
TRS 3.0 updated working draft

### PR DESCRIPTION
**Pull request by ndjc**
TRS 3.0 draft now ready for review by the open project members.

### CODE REVIEW

**Review by berezovskyi — CHANGES_REQUESTED** [review]
Please update status from PND to WD and we can merge!

**Comment by ndjc** [comment]
btw, I do not know why the system thinks I have not signed a CLA. If I follow any of the links from that check, I see that I have, and the right email addresses are associated with the GitHub account.

**Comment by ndjc** [comment]
@berezovskyi the status of the TRS spec is WD. The status of the guidance.html is PND, because I expect that to be merged into David's primer and then deleted; it is not part of the spec.

**Review by berezovskyi — APPROVED** [review]
My bad!

**Comment by berezovskyi** [comment]
https://github.com/oslc-op/oslc-specs/commit/31da8ff92343df041447d08e006210a81a3b511a.patch has a bad email, that's why.

I will now squash and merge

**Comment by berezovskyi** [comment]
hmm, it cannot be merged to master, actually, there are some conflicts

**Comment by berezovskyi** [comment]
nevermind, it's the rebase of all 19 commits that had conflicts; squashing into a single commit went fine

**Review by img — COMMENTED** [review]
Review of sections 1-10.
section 2:
“An HTTP GET request sent to the Tracked Resource Set URI returns a representation…” this is an unusual way to describe a GET?

“The Change Log provides a (possibly empty) time-ordered series of adjustments…”.  I always thought of the ordering as independent from time.. is this not the case?  

“up to date” -> “up-to-date”, at least to agree with “point-in-time”?

“The Change Log portion can contain” --> delete “portion”

section 3
“TRS Clients use the Base to establish the resources to track, and the Change Log to address changes to those resources” not sure that this is helpful, might be misleading.

“The Tracked Resource Set resource is the object” --> incomplete sentence?  Append “of this assertion”

section 5.1
time-ordered? or simply ordered by trs:order?

section 5.2
“A resource type URI. Clients can infer a resource type of” ought this to be a SHOULD?  Don't we want to encourange use of rdf:type in this case?

trs:cutoffEvent description is quite dense.  Perhaps this should be moved into a paragraph?

section 5.3
” The URI is only used to identify an event” seems informal.  isn’t it enough to say it’s a URI that does not need to be dereferenceable?
“even in the wake of a Server rollback where order numbers get reused”. this reads like a requirement on the reuse of trs:order values.  I don’t think that is the intention. suggest “may” (little may).

section 5.4
trspatch:afterETag is there a need to clarify the etag in the case the resource is paged?  I don't remember if oslc paging makes the distinction between resource etag and etags of its paged representations.
“A patch is meaningful only for resources with RDF representations. which oslc resources do not have rdf representations?

section 6
capitalization of “tracked resource” etc.  We ought to be be consistent.

Is it worth point out that consistency of the change log wrt the server data is only required for the entire changelog (that is, not some tail of the changelog).  A client cannot ignore an initial prefix of the changelog and expect consistency with some earlier point-in-time of the server’s data.

“A Server MUST eventually report a change event for a tracked resource if at time t0,”.  Do we want some non-normative explanation here as to what “eventually” is taken to mean?

para 4, the consistency statement is too strong and perhaps inconsistent with paras 2 and 3.  it excludes the case that at t1 (>t0) a complementary nullifying change happens to that same resource.  the change log should not be required to distinguish these events.  as written, this also seems to be at odds with the second para of section 6.  the statement “When a resource is created and deleted in rapid succession” touches on this.

“A Server MAY issue a deletion event for a resource that is not a member of the Tracked Resource Set, and MAY issue multiple deletion events for a member of the Tracked Resource Set.” is the second clause required?  once deleted, it is not in the TRS.

“When a resource is created and deleted in rapid succession”.  “rapid” is not defined. I think we need a more succint characterization of eventual consistency.

section 7
“each one containing earlier and earlier events” suggest “lower ordered” 
do we not want a constraint that for any two changelog segments s0 and s1, where s1 trs:previous s0, that all the events in s1 are trs:ordered > all events in s0?   Otherwise, clients need to consume all segments to determine all trs:orders.

section 9
“A Server MAY move or copy a change event from one segment” what does “copy” mean wrt uniqueness of the Uri of the event?

**Comment by ndjc** [comment]
I have addressed each of @img issues except these:

> section 5.2 “A resource type URI. Clients can infer a resource type of” ought this to be a SHOULD?

While I sympathize with this suggestion, I have not incorporated it yet. Existing code probably does not provide either the brand-new type trs:Base, nor the older ldp:DirectContainer supertype.

> trspatch:afterETag is there a need to clarify the etag in the case the resource is paged? I don't remember if oslc paging makes the distinction between resource etag and etags of its paged representations.

Good question. I've left this unresolved pending current discussions on paging in general.

> para 4, the consistency statement is too strong and perhaps inconsistent with paras 2 and 3.

I do not believe this is the case, since the rule is qualified by "such that a GET on that resource would now return a semantically different response".

> Do we want some non-normative explanation here as to what “eventually” is taken to mean?
> “rapid” is not defined. I think we need a more succint characterization of eventual consistency.

See the separate section on timescales, which provides just that non-normative explanation. I do not see any way of providing more explicit rules in a general-purpose specification.

**Pull request merged**
