### PR TITLE
Reorganise RDF files for the RM spec

### LINKED ISSUE #85: Two RM vocabs exist
See specs/rm/requirements-management-vocab.ttl and specs/rm/rm.ttl

### LINKED ISSUE #86: RM vocab removes inverse properties
Related to #85 and #82.

I assume this is the normative vocab: specs/rm/requirements-management-vocab.ttl

The properties already in use since 2.0 shall not be removed.

### PR DESCRIPTION
**Pull request by berezovskyi**
- rm.xml and rm.ttl were isomorphic. XML was removed and Turtle was 
formatted with Jena RIOT formatter into rm_jra.ttl
- rm.rdf was renamed into rm_2.0.xml (for history) and converted into 
Turtle file rm_2.0.ttl
- the current vocab file was reformatted.

Closes #85, closes #86.

### CODE REVIEW

**Comment by berezovskyi** [comment]
This is a work in progress, but the plan is to replace all the vocabs with the one based on Jim's definitions as it is the only one with the missing properties.

**Comment by berezovskyi** [comment]
I would also like not to merge it until it passes all SC checks.

**Comment by jadelkhoury** [comment]
A summary of the last commit. (Pushed prematurely before I could enter a proper message)

1. I identified and added 2 missing "by" properties that existed in the shapes, but not the vocab.

- oslc_rm:decomposedBy
- oslc_rm:constrainedBy

2. I added these "inverse" properties that existed in the shapes, but not the vocab.
- oslc_rm:satisfies
- oslc_rm:elaborates
- oslc_rm:specifies
- oslc_rm:decomposes
- oslc_rm:constrains

3. I only elaborated  the description of the "satisfies" property. I thought we agree on the format of the description before I can elaborate the remaining ones.

Note, it is interesting that the following do not have an inverse property:
- implementedBy
- trackedBy
- affectedBy
- validatedBy

**Comment by jadelkhoury** [comment]
@berezovskyi I cannot add you as a reviewer.

**Comment by berezovskyi** [comment]
@jadelkhoury, great work!

> I identified and added 2 missing "by" properties that existed in the shapes, but not the vocab.

perfect!

> I added these "inverse" properties that existed in the shapes, but not the vocab.

👌 

> rdfs:comment "Expresses the inverse property of oslc_rm:satisfiedBy"

I think this one is a bit dangerous given that Jim and Nick are manifestly against adding an `owl:inverseOf`. We need to word it so that the ontologists will not misunderstand it. I suggest to call them _backlinks_ instead of _inverse properties._ 

> @berezovskyi I cannot add you as a reviewer.

I created the PR originally and cannot review my own work :)

> Conflicting files

Sorry for that, I just merged #118 first :) If you need help resolving the merge conflict, I am here to help.

**Comment by berezovskyi** [comment]
> It is interesting that the following do not have an inverse property.

I would be in favour of adding them in the vocabulary and let the implementors decide if using them is worth the trouble.

**Comment by jamsden** [comment]
I recommend avoiding all words like inverse, backlink, reverse, etc. These are just properties with no implications concerning covariance. The fact that the RM spec is defining them in both directions is already problem enough. Link guidance will need to address this case specifically. It might even be useful to make a note in the RM spec to guide server implementations.

**Comment by jadelkhoury** [comment]
We do need some basic text to describe what this property is. Not sure what we can say if we are to avoid words like inverse, backlink, .... I certainly agree we should not even mention owl:inverseOf, but we can't be afraid of using basic english words just in case ontologists might misundertand it.
     "Expresses the inverse property of xxx" is quite minimal.

I agree otherwise that we can make a note in the RM spec to guide server implementations. In general, I think we need to explain the meaning of this 1 resource shape we are defining in the specs. (given that one can have different resource shapes for different purposes - creation, update, query, etc.)

**Comment by berezovskyi** [comment]
True.

I just thought it would be harder to mistakenly assume inverseOf when reading that something is a backlink as compared to inverse...

--
/Andrew
(from phone)

29 aug. 2019 kl. 22:12 skrev Jad El-khoury <notifications@github.com<mailto:notifications@github.com>>:


We do need some basic text to describe what this property is. Not sure what we can say if we are to avoid words like inverse, backlink, .... I certainly agree we should not even mention owl:inverseOf, but we can't be afraid of using basic english words just in case ontologists might misundertand it.
"Expresses the inverse property of xxx" is quite minimal.

I agree otherwise that we can make a note in the RM spec to guide server implementations. In general, I think we need to explain the meaning of this 1 resource shape we are defining in the specs. (given that one can have different resource shapes for different purposes - creation, update, query, etc.)

**Comment by jamsden** [comment]
Example: 
implementedBy (i.e., requirement implementedBy change request): Indicates the requirement is implemented by the target change request (or something similar).

implements (i.e., change request implements requirement): Indicates a change request that implements this requirement. 

There's no need for these properties to reference each other at all.

**Comment by berezovskyi** [comment]
@jadelkhoury just decide and do as you think is best

**Comment by berezovskyi** [comment]
I have added a config: https://github.com/oslc-op/oslc-specs/pull/119/commits/a73f28b01f7b49e7f27d63e3a6c685d790ba37cb

But also did a merge for the vocabs: https://github.com/oslc-op/oslc-specs/pull/119/commits/7a0f06f457cda5d9eb3e641f283f5fa110a650d7 This may look scary big but your vocab is mostly unchanged: https://github.com/oslc-op/oslc-specs/pull/119/files/ff1a660c39454345261aa368a1429278eede9c0a..7a0f06f457cda5d9eb3e641f283f5fa110a650d7?file-filters%5B%5D=.ttl#diff-b3562879505ac80b83db096930018c39 (just an Apache header added)

@jadelkhoury here is the output from the build:

> Checked vocabulary http://open-services.net/ns/rm# from file:/home/circleci/oslc-specs/tools/ShapeChecker/../../specs/rm/requirements-management-vocab.ttl, with 3 issues (0 info, 3 warnings, 0 errors)
>    While examining vocabulary term http://open-services.net/ns/rm#RequirementCollection:
>       Warning on http://open-services.net/ns/core#hasBasicShape: This property is unexpected. (bad value http://open-services-net/shapes/rm#requirementCollectionShape)
>    While examining vocabulary term http://open-services.net/ns/rm#Requirement:
>       Warning on http://open-services.net/ns/core#hasBasicShape: This property is unexpected. (bad value http://open-services.net/ns/rm#requirementShape)
>    While examining ontology http://open-services.net/ns/rm#:
>       Warning on https://github.com/oslc-op/oslc-specs/blob/master/specs/blob/master/rm/requirements-management-vocab.ttl: This resource is not fetchable. (bad value 404)
>

**Comment by jadelkhoury** [comment]
I am very fine with @jamsden 's suggestion. I will update accordingly.

**Comment by jadelkhoury** [comment]
so, what do you think of the latest changes then?

**Comment by berezovskyi** [comment]
Good to merge

**Comment by ndjc** [comment]
Need review from @img.

**Comment by berezovskyi** [comment]
Agreed as ready to merge today during the call.

**Pull request merged**
