### PR TITLE
Add a SCheck config for CM

### LINKED ISSUE #114: Enable ShapeChecker on CM shapes
Before we promote it to the PS stage.

### PR DESCRIPTION
**Pull request by berezovskyi**
Resolves #114

### CODE REVIEW

**Comment by berezovskyi** [comment]
@jamsden I think this is ready to merge. CM vocabs & shapes pass the test and we will detect if something goes wrong in the future.

<details>
<summary>Output for the CM</summary>
Results from ShapeChecker run on Fri Aug 30 19:49:00 UTC 2019

Command line arguments:
   -x http://open-services.net/ns/core -x http://open-services.net/ns/cm -v ../../specs/core/vocab/core-vocab.ttl -v
   ../../specs/cm/change-mgt-vocab.ttl -s ../../specs/cm/change-mgt-shapes.ttl

A total of 143 issues were found (143 info, 0 warnings, 0 errors)

Checked vocabulary http://open-services.net/ns/cm# from file:/home/circleci/oslc-specs/tools/ShapeChecker/../../specs/cm/change-mgt-vocab.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked vocabulary http://open-services.net/ns/core# from file:/home/circleci/oslc-specs/tools/ShapeChecker/../../specs/core/vocab/core-vocab.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/home/circleci/oslc-specs/tools/ShapeChecker/../../specs/cm/change-mgt-shapes.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Info: These 143 terms were defined in the given vocabularies, but not referenced in the given shapes:
   http://open-services.net/ns/cm#Approved
   http://open-services.net/ns/cm#Blocker
   http://open-services.net/ns/cm#Closed
   http://open-services.net/ns/cm#Critical
   http://open-services.net/ns/cm#Fixed
   http://open-services.net/ns/cm#High
   http://open-services.net/ns/cm#Inprogress
   http://open-services.net/ns/cm#Low
   http://open-services.net/ns/cm#Major
   http://open-services.net/ns/cm#Medium
   http://open-services.net/ns/cm#Minor
   http://open-services.net/ns/cm#Normal
   http://open-services.net/ns/cm#Priority
   http://open-services.net/ns/cm#PriorityUnassigned
   http://open-services.net/ns/cm#Reviewed
   http://open-services.net/ns/cm#Severity
   http://open-services.net/ns/cm#SeverityUnassigned
   http://open-services.net/ns/cm#State
   http://open-services.net/ns/cm#Verified
   http://open-services.net/ns/cm#affectsTestResult
   http://open-services.net/ns/cm#blocksTestExecutionRecord
   http://open-services.net/ns/cm#defect
   http://open-services.net/ns/cm#planItem
   http://open-services.net/ns/cm#relatedTestCase
   http://open-services.net/ns/cm#relatedTestExecutionRecord
   http://open-services.net/ns/cm#relatedTestPlan
   http://open-services.net/ns/cm#relatedTestScript
   http://open-services.net/ns/cm#requirementsChangeRequest
   http://open-services.net/ns/cm#task
   http://open-services.net/ns/cm#testedByTestCase
   http://open-services.net/ns/core#AllowedValues
   http://open-services.net/ns/core#Any
   http://open-services.net/ns/core#AnyResource
   http://open-services.net/ns/core#AttachmentContainer
   http://open-services.net/ns/core#AttachmentDescriptor
   http://open-services.net/ns/core#Cardinality
   http://open-services.net/ns/core#Comment
   http://open-services.net/ns/core#Compact
   http://open-services.net/ns/core#CreationFactory
   http://open-services.net/ns/core#Dialog
   http://open-services.net/ns/core#Discussion
   http://open-services.net/ns/core#Either
   http://open-services.net/ns/core#Error
   http://open-services.net/ns/core#Exactly-one
   http://open-services.net/ns/core#ExtendedError
   http://open-services.net/ns/core#ImpactFollowsLink
   http://open-services.net/ns/core#ImpactOppositeLink
   http://open-services.net/ns/core#ImpactType
   http://open-services.net/ns/core#Inline
   http://open-services.net/ns/core#LocalResource
   http://open-services.net/ns/core#NoImpact
   http://open-services.net/ns/core#OAuthConfiguration
   http://open-services.net/ns/core#One-or-many
   http://open-services.net/ns/core#PrefixDefinition
   http://open-services.net/ns/core#Preview
   http://open-services.net/ns/core#Property
   http://open-services.net/ns/core#Publisher
   http://open-services.net/ns/core#QueryCapability
   http://open-services.net/ns/core#Reference
   http://open-services.net/ns/core#Representation
   http://open-services.net/ns/core#Resource
   http://open-services.net/ns/core#ResourceShape
   http://open-services.net/ns/core#ResourceValueType
   http://open-services.net/ns/core#ResponseInfo
   http://open-services.net/ns/core#Service
   http://open-services.net/ns/core#ServiceProvider
   http://open-services.net/ns/core#ServiceProviderCatalog
   http://open-services.net/ns/core#SymmetricImpact
   http://open-services.net/ns/core#Zero-or-many
   http://open-services.net/ns/core#Zero-or-one
   http://open-services.net/ns/core#allowedValue
   http://open-services.net/ns/core#allowedValues
   http://open-services.net/ns/core#archived
   http://open-services.net/ns/core#attachment
   http://open-services.net/ns/core#attachmentSize
   http://open-services.net/ns/core#authorizationURI
   http://open-services.net/ns/core#comment
   http://open-services.net/ns/core#creation
   http://open-services.net/ns/core#creationDialog
   http://open-services.net/ns/core#creationFactory
   http://open-services.net/ns/core#default
   http://open-services.net/ns/core#defaultValue
   http://open-services.net/ns/core#describes
   http://open-services.net/ns/core#details
   http://open-services.net/ns/core#dialog
   http://open-services.net/ns/core#discussionAbout
   http://open-services.net/ns/core#document
   http://open-services.net/ns/core#domain
   http://open-services.net/ns/core#error
   http://open-services.net/ns/core#executes
   http://open-services.net/ns/core#extendedError
   http://open-services.net/ns/core#futureAction
   http://open-services.net/ns/core#hidden
   http://open-services.net/ns/core#hintHeight
   http://open-services.net/ns/core#hintWidth
   http://open-services.net/ns/core#icon
   http://open-services.net/ns/core#iconAltLabel
   http://open-services.net/ns/core#iconSrcSet
   http://open-services.net/ns/core#iconTitle
   http://open-services.net/ns/core#impactType
   http://open-services.net/ns/core#inReplyTo
   http://open-services.net/ns/core#initialHeight
   http://open-services.net/ns/core#inverseLabel
   http://open-services.net/ns/core#isMemberProperty
   http://open-services.net/ns/core#label
   http://open-services.net/ns/core#largePreview
   http://open-services.net/ns/core#maxSize
   http://open-services.net/ns/core#message
   http://open-services.net/ns/core#modifiedBy
   http://open-services.net/ns/core#moreInfo
   http://open-services.net/ns/core#name
   http://open-services.net/ns/core#nextPage
   http://open-services.net/ns/core#oauthAccessTokenURI
   http://open-services.net/ns/core#oauthConfiguration
   http://open-services.net/ns/core#oauthRequestTokenURI
   http://open-services.net/ns/core#occurs
   http://open-services.net/ns/core#partOfDiscussion
   http://open-services.net/ns/core#postBody
   http://open-services.net/ns/core#prefix
   http://open-services.net/ns/core#prefixBase
   http://open-services.net/ns/core#prefixDefinition
   http://open-services.net/ns/core#property
   http://open-services.net/ns/core#propertyDefinition
   http://open-services.net/ns/core#queryBase
   http://open-services.net/ns/core#queryCapability
   http://open-services.net/ns/core#queryable
   http://open-services.net/ns/core#range
   http://open-services.net/ns/core#readOnly
   http://open-services.net/ns/core#rel
   http://open-services.net/ns/core#representation
   http://open-services.net/ns/core#resourceShape
   http://open-services.net/ns/core#resourceType
   http://open-services.net/ns/core#results
   http://open-services.net/ns/core#selectionDialog
   http://open-services.net/ns/core#service
   http://open-services.net/ns/core#serviceProviderCatalog
   http://open-services.net/ns/core#shortId
   http://open-services.net/ns/core#smallPreview
   http://open-services.net/ns/core#statusCode
   http://open-services.net/ns/core#totalCount
   http://open-services.net/ns/core#usage
   http://open-services.net/ns/core#valueShape
   http://open-services.net/ns/core#valueType
</details>

**Comment by ndjc** [comment]
Why do you include the Core vocal in the CM ShapeCheck?

**Comment by ndjc** [comment]
Sorry - closed by mistake

**Comment by berezovskyi** [comment]
I wanted to prevent it from fetching them and instead use the ones in the repo. Is it the right way to do it? Does it even make sense to do it?

**Comment by ndjc** [comment]
It's OK if you want to cross-check with the Core vocabulary, which can be of value to detect typos, etc.
I have no other comments - go ahead with this one.

**Pull request merged**
