### PR TITLE
B cfg prettier

### LINKED ISSUE #415: Remove prev stage from CfgM
OASIS only cares about PSD/CSPRD references and above

### PR DESCRIPTION
**Pull request by ndjc**
Merge changes for prettier back to master:

- Run `prettier --write` on config mgt sources;
- Use a new script `prettier-main.sh` to run all prettier checks from CircleCI, not stopping on first fail (just as was done previously for ShapeChecker tests);
- Fixes #415.

### CODE REVIEW

**Review by berezovskyi — CHANGES_REQUESTED** [review]
Nick, thanks for the fixes. The only request is to remove the bash script, I really prefer UI signals to reading error logs. I used https://circleci.com/docs/2.0/configuration-reference/#the-when-attribute attribute to ensure all steps are executed even if the build error was enountered before.

**Comment by berezovskyi** [comment]
image

I believe this makes it obvious whose spec is breaking the build. @jamsden @jadelkhoury, what's your take on this?

**Comment by berezovskyi** [comment]
@ndjc wonderful! Let me add prettierrc and lock the version to avoid this mess in the future and then we can merge

**Comment by ndjc** [comment]
OK, I've removed the shell script, but added to config.yml the config mgt prettier check that I had put in the script.

**Review by berezovskyi — APPROVED** [review]

**Pull request merged**
