### PR TITLE
Fix SC vocabulary fetching

### PR DESCRIPTION
**Pull request by berezovskyi**
Changes:

- removed Nick's fix for the dcterms URIs specifically
- switched to a more sophisticated method of parsing a remote Jena model source
- forcibly added the Accept header to make sure it's not lost across redirects

see #320 #88

### CODE REVIEW

**Comment by berezovskyi** [comment]
I think there is a problem with the Jena that it does not always carry Accept headers through redirects and it causes DCTerms to return text/html at some point, which sets it all on fire. I think this behaviour from Jena can cause problems (RDFParser:390 ignores previously set RDFParserBuilder.httpAccept), so I forced it to always have a near-complete RDF Accept header. Also, Jena requests `application/rdf+xml, application/xml; q=0.8, text/xml; q=0.7, application/rss+xml; q=0.3, */*; q=0.2` but should be at least `text/turtle;application/n-triples;application/rdf+xml;application/ld+json`.

However, I am still getting a few problems:

```
➜  ShapeChecker git:(b-sc-dcterms) ✗ ./check-core-strict.sh
[main] WARN org.apache.http.client.protocol.ResponseProcessCookies - Invalid cookie header: "Set-Cookie: _octo=GH1.1.1645234904.1591284737; Path=/; Domain=github.com; Expires=Fri, 04 Jun 2021 15:32:17 GMT; Secure; SameSite=Lax". Invalid 'expires' attribute: Fri, 04 Jun 2021 15:32:17 GMT
[main] WARN org.apache.http.client.protocol.ResponseProcessCookies - Invalid cookie header: "Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Fri, 04 Jun 2021 15:32:17 GMT; HttpOnly; Secure; SameSite=Lax". Invalid 'expires' attribute: Fri, 04 Jun 2021 15:32:17 GMT
[main] ERROR org.apache.jena.riot - [line: 2, col: 14] Triples not terminated by DOT
[main] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://purl.org:80: The target server failed to respond
[main] INFO org.apache.http.impl.execchain.RetryExec - Retrying request to {}->http://purl.org:80
[main] ERROR org.apache.jena.riot - [line: 2, col: 14] Triples not terminated by DOT
[main] ERROR org.apache.jena.riot - [line: 2, col: 14] Triples not terminated by DOT
[main] ERROR org.apache.jena.riot - [line: 2, col: 14] Triples not terminated by DOT
[main] ERROR org.apache.jena.riot - [line: 2, col: 14] Triples not terminated by DOT
[main] ERROR org.apache.jena.riot - [line: 2, col: 14] Triples not terminated by DOT
[main] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://purl.org:80: The target server failed to respond
[main] INFO org.apache.http.impl.execchain.RetryExec - Retrying request to {}->http://purl.org:80
[main] ERROR org.apache.jena.riot - [line: 2, col: 14] Triples not terminated by DOT
[main] ERROR org.apache.jena.riot - [line: 2, col: 14] Triples not terminated by DOT
[main] ERROR org.apache.jena.riot - [line: 2, col: 14] Triples not terminated by DOT
[main] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://purl.org:80: The target server failed to respond
[main] INFO org.apache.http.impl.execchain.RetryExec - Retrying request to {}->http://purl.org:80
[main] ERROR org.apache.jena.riot - [line: 2, col: 14] Triples not terminated by DOT
[main] ERROR org.apache.jena.riot - [line: 2, col: 14] Triples not terminated by DOT
[main] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://www.w3.org:80: The target server failed to respond
[main] INFO org.apache.http.impl.execchain.RetryExec - Retrying request to {}->http://www.w3.org:80
[main] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://purl.org:80: The target server failed to respond
[main] INFO org.apache.http.impl.execchain.RetryExec - Retrying request to {}->http://purl.org:80
[main] ERROR org.apache.jena.riot - [line: 2, col: 14] Triples not terminated by DOT
Results from ShapeChecker run on Thu Jun 04 17:32:16 CEST 2020

Command line arguments:
   -x http://open-services.net/ns/core -x http://open-services.net/ns/core#.* -v ../../specs/core/vocab/core-vocab.ttl -s
   ../../specs/core/shapes/AttachmentDescriptor-shape.ttl -s ../../specs/core/shapes/Comment-shape.ttl -s
   ../../specs/core/shapes/CommonProperties-shape.ttl -s ../../specs/core/shapes/Compact-shape.ttl -s
   ../../specs/core/shapes/CreationFactory-shape.ttl -s ../../specs/core/shapes/Dialog-shape.ttl -s
   ../../specs/core/shapes/Discussion-shape.ttl -s ../../specs/core/shapes/Error-shape.ttl -s
   ../../specs/core/shapes/ExtendedError-shape.ttl -s ../../specs/core/shapes/OAuthConfiguration-shape.ttl -s
   ../../specs/core/shapes/PrefixDefinition-shape.ttl -s ../../specs/core/shapes/Preview-shape.ttl -s
   ../../specs/core/shapes/Publisher-shape.ttl -s ../../specs/core/shapes/QueryCapability-shape.ttl -s
   ../../specs/core/shapes/ResourceShapes-shape.ttl -s ../../specs/core/shapes/ResponseInfo-shape.ttl -s
   ../../specs/core/shapes/Service-shape.ttl -s ../../specs/core/shapes/ServiceProvider-shape.ttl -s
   ../../specs/core/shapes/ServiceProviderCatalog-shape.ttl

A total of 49 issues were found (32 info, 5 warnings, 12 errors)

Checked vocabulary http://open-services.net/ns/core# from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/vocab/core-vocab.ttl, with 4 issues (0 info, 4 warnings, 0 errors)
   While examining ontology http://open-services.net/ns/core#:
      Warning on http://open-services.net/ns/core#: This property is unexpected. (bad value http://purl.org/dc/terms/modified)
      Warning on http://open-services.net/ns/core#: This property is unexpected. (bad value http://purl.org/dc/terms/hasVersion)
      Warning on http://open-services.net/ns/core#: This property is unexpected. (bad value http://purl.org/dc/terms/publisher)
      Warning on http://open-services.net/ns/core#: This property is unexpected. (bad value http://purl.org/dc/terms/isPartOf)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/PrefixDefinition-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/Dialog-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/Error-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/Discussion-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/Publisher-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/Service-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/AttachmentDescriptor-shape.ttl, with 6 issues (0 info, 0 warnings, 6 errors)
   While examining resource shape http://open-services.net/ns/core/shapes/3.0/AttachmentDescriptor-shape.ttl#AttachmentDescriptor:
      While examining property definition http://open-services.net/ns/core/shapes/3.0/AttachmentDescriptor-shape.ttl#dcterms-desc:
         Error on http://purl.org/dc/terms/description: The target resource cannot be fetched or parsed as RDF. (bad value org.apache.jena.riot.RiotException: [line: 2, col: 14] Triples not terminated by DOT)
      While examining property definition http://open-services.net/ns/core/shapes/3.0/AttachmentDescriptor-shape.ttl#dcterms-created:
         Error on http://purl.org/dc/terms/created: The target resource cannot be fetched or parsed as RDF. (bad value org.apache.jena.riot.RiotException: [line: 2, col: 14] Triples not terminated by DOT)
      While examining property definition http://open-services.net/ns/core/shapes/3.0/AttachmentDescriptor-shape.ttl#dcterms-title:
         Error on http://purl.org/dc/terms/title: The target resource cannot be fetched or parsed as RDF. (bad value org.apache.jena.riot.RiotException: [line: 2, col: 14] Triples not terminated by DOT)
      While examining property definition http://open-services.net/ns/core/shapes/3.0/AttachmentDescriptor-shape.ttl#dcterms-format:
         Error on http://purl.org/dc/terms/format: The target resource cannot be fetched or parsed as RDF. (bad value org.apache.jena.riot.RiotException: [line: 2, col: 14] Triples not terminated by DOT)
      While examining property definition http://open-services.net/ns/core/shapes/3.0/AttachmentDescriptor-shape.ttl#dcterms-creator:
         Error on http://purl.org/dc/terms/creator: The target resource cannot be fetched or parsed as RDF. (bad value org.apache.jena.riot.RiotException: [line: 2, col: 14] Triples not terminated by DOT)
      While examining property definition http://open-services.net/ns/core/shapes/3.0/AttachmentDescriptor-shape.ttl#dcterms-id:
         Error on http://purl.org/dc/terms/identifier: The target resource cannot be fetched or parsed as RDF. (bad value org.apache.jena.riot.RiotException: [line: 2, col: 14] Triples not terminated by DOT)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/Preview-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/ResourceShapes-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/CreationFactory-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/Compact-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/ServiceProvider-shape.ttl, with 1 issue (0 info, 0 warnings, 1 errors)
   While examining resource shape http://open-services.net/ns/core/shapes/3.0/ServiceProvider-shape.ttl#ServiceProvider:
      While examining property definition http://open-services.net/ns/core/shapes/3.0/ServiceProvider-shape.ttl#dcterms-publisher:
         Error on http://purl.org/dc/terms/publisher: The target resource cannot be fetched or parsed as RDF. (bad value org.apache.jena.riot.RiotException: [line: 2, col: 14] Triples not terminated by DOT)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/OAuthConfiguration-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/CommonProperties-shape.ttl, with 6 issues (0 info, 1 warnings, 5 errors)
   While examining resource shape http://open-services.net/ns/core/shapes/3.0/CommonProperties-shape.ttl#CommonProperties:
      Warning on http://open-services.net/ns/core#describes: The named property should be specified for this resource.
      While examining property definition http://open-services.net/ns/core/shapes/3.0/CommonProperties-shape.ttl#subject:
         Error on http://purl.org/dc/terms/subject: The target resource cannot be fetched or parsed as RDF. (bad value org.apache.jena.riot.RiotException: [line: 2, col: 14] Triples not terminated by DOT)
      While examining property definition http://open-services.net/ns/core/shapes/3.0/CommonProperties-shape.ttl#references:
         Error 	: The target resource cannot be fetched or parsed as RDF. (bad value org.apache.jena.riot.RiotException: [line: 2, col: 14] Triples not terminated by DOT)
      While examining property definition http://open-services.net/ns/core/shapes/3.0/CommonProperties-shape.ttl#contributor:
         Error on http://purl.org/dc/terms/contributor: The target resource cannot be fetched or parsed as RDF. (bad value org.apache.jena.riot.RiotException: [line: 2, col: 14] Triples not terminated by DOT)
      While examining property definition http://open-services.net/ns/core/shapes/3.0/CommonProperties-shape.ttl#modified:
         Error on http://purl.org/dc/terms/modified: The target resource cannot be fetched or parsed as RDF. (bad value org.apache.jena.riot.RiotException: [line: 2, col: 14] Triples not terminated by DOT)
      While examining property definition http://open-services.net/ns/core/shapes/3.0/CommonProperties-shape.ttl#relation:
         Error on http://purl.org/dc/terms/relation: The target resource cannot be fetched or parsed as RDF. (bad value org.apache.jena.riot.RiotException: [line: 2, col: 14] Triples not terminated by DOT)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/ResponseInfo-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/ServiceProviderCatalog-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/QueryCapability-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/ExtendedError-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Checked shapes from file:/Users/ezandbe/git/oslc/oslc-specs/tools/ShapeChecker/../../specs/core/shapes/Comment-shape.ttl, with 0 issues (0 info, 0 warnings, 0 errors)

Info: These 32 terms were defined in the given vocabularies, but not referenced in the given shapes:
   http://open-services.net/ns/core#Any
   http://open-services.net/ns/core#AnyResource
   http://open-services.net/ns/core#AttachmentContainer
   http://open-services.net/ns/core#Cardinality
   http://open-services.net/ns/core#Either
   http://open-services.net/ns/core#Exactly-one
   http://open-services.net/ns/core#ImpactFollowsLink
   http://open-services.net/ns/core#ImpactOppositeLink
   http://open-services.net/ns/core#ImpactType
   http://open-services.net/ns/core#Inline
   http://open-services.net/ns/core#LocalResource
   http://open-services.net/ns/core#NoImpact
   http://open-services.net/ns/core#One-or-many
   http://open-services.net/ns/core#Reference
   http://open-services.net/ns/core#Representation
   http://open-services.net/ns/core#Resource
   http://open-services.net/ns/core#ResourceValueType
   http://open-services.net/ns/core#SymmetricImpact
   http://open-services.net/ns/core#Zero-or-many
   http://open-services.net/ns/core#Zero-or-one
   http://open-services.net/ns/core#attachment
   http://open-services.net/ns/core#default
   http://open-services.net/ns/core#executes
   http://open-services.net/ns/core#futureAction
   http://open-services.net/ns/core#impactType
   http://open-services.net/ns/core#initialHeight
   http://open-services.net/ns/core#inverseLabel
   http://open-services.net/ns/core#order
   http://open-services.net/ns/core#partOfDiscussion
   http://open-services.net/ns/core#publisher
   http://open-services.net/ns/core#results
   http://open-services.net/ns/core#score
```

@ndjc what am I missing?

Just for posterity, here is the list of all redirects (output edited):

```
➜  ShapeChecker git:(b-sc-dcterms) ✗ curl -L -H "Accept: text/turtle;application/n-triples;application/rdf+xml;application/ld+json" http://purl.org/dc/terms/contributor -v
*   Trying 207.241.224.2...
* TCP_NODELAY set
* Connected to purl.org (207.241.224.2) port 80 (#0)
> GET /dc/terms/contributor HTTP/1.1
> Host: purl.org
> User-Agent: curl/7.54.0
> Accept: text/turtle;application/n-triples;application/rdf+xml;application/ld+json
>
< HTTP/1.1 302 FOUND
< Server: nginx/1.16.1 (Ubuntu)
< Date: Thu, 04 Jun 2020 15:56:52 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 253
< Connection: keep-alive
< Location: https://dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_terms#contributor
< Access-Control-Allow-Origin: *
<
> GET /specifications/dublin-core/dcmi-terms/dublin_core_terms HTTP/2
> Host: dublincore.org
> User-Agent: curl/7.54.0
> Accept: text/turtle;application/n-triples;application/rdf+xml;application/ld+json
>
< HTTP/2 303
< server: nginx/1.17.8
< date: Thu, 04 Jun 2020 15:56:53 GMT
< content-type: text/html; charset=iso-8859-1
< content-length: 288
< location: http://dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_terms.ttl
< strict-transport-security: max-age=15724800; includeSubDomains
<
* Ignoring the response-body
* Connection #1 to host dublincore.org left intact
* Issue another request to this URL: 'http://dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_terms.ttl'
* Connection 1 seems to be dead!
* Connected to dublincore.org (104.200.23.106) port 80 (#2)
> GET /specifications/dublin-core/dcmi-terms/dublin_core_terms.ttl HTTP/1.1
> Host: dublincore.org
> User-Agent: curl/7.54.0
> Accept: text/turtle;application/n-triples;application/rdf+xml;application/ld+json
>
< HTTP/1.1 308 Permanent Redirect
< Server: nginx/1.17.8
< Date: Thu, 04 Jun 2020 15:56:54 GMT
< Content-Type: text/html
< Location: https://dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_terms.ttl
<
* Ignoring the response-body
> GET /specifications/dublin-core/dcmi-terms/dublin_core_terms.ttl HTTP/2
> Host: dublincore.org
> User-Agent: curl/7.54.0
> Accept: text/turtle;application/n-triples;application/rdf+xml;application/ld+json
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< server: nginx/1.17.8
< date: Thu, 04 Jun 2020 15:56:54 GMT
< content-type: text/turtle
<
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
```

**Comment by berezovskyi** [comment]
`Retrying request to {}->http://purl.org:80` seems to be caused by the first server closing the connection despite the keep-alive request. Which is fine. We should tune timeouts to figure out the connection was closed for good a bit faster.

`HTTP/1.1 302 FOUND \n Content-Type: text/html; charset=utf-8` could have indeed confused Jena and conclude it was HTML that is was getting. Same for the following 303 and 308 redirects. I think one way to deal with it is to make sure only Content-Type headers from 2xx resposes are used for conneg.

**Comment by jamsden** [comment]
Very good. Thank you!

**Comment by berezovskyi** [comment]
Great, thank you for getting to the bottom of this!

**Comment by ndjc** [comment]
btw, I'm confused as to why this was merged into the branch jra-am-v3.0-psd01 as opposed to master? What's the timeline for getting these changes into master?

**Comment by berezovskyi** [comment]
Was my blunder. The branch was created off the jra and PR to master had too many unrelated changes. I had to make PR against Jim’s branch. Both PR are now on master.

Cheers,
Andrew

________________________________

**Pull request merged**
