### PR TITLE
Update RM for ReSpec 2.1.10

### PR DESCRIPTION
**Pull request by berezovskyi**
See https://github.com/oasis-tcs/tab-respec/pull/6

### CODE REVIEW

**Comment by berezovskyi** [comment]
image

**Comment by jamsden** [comment]
OASIS has removed the indent for all this version related content. We should probably do that to avoid an issue. 

The Additional components should only have the file names (relative links).

What will the PSD look like?

**Comment by berezovskyi** [comment]
@jamsden will be fixed

**Comment by berezovskyi** [comment]
@jamsden @jadelkhoury just updated to include all the changes done on CM for ReSpec 2.1.6:

image

**Comment by berezovskyi** [comment]
@jadelkhoury please use 2.1.7. No compat issues from 2.1.6.

**Comment by berezovskyi** [comment]
@jadelkhoury could you please update RM to use ReSpec 2.1.8, please? I think it will be good to publish an RM PSD next.

**Comment by berezovskyi** [comment]
ReSpec 2.1.9 has the changes requested by Paul for the CM PSD, but not released yet. See https://github.com/oasis-tcs/tab-respec/pull/11

**Comment by berezovskyi** [comment]
Updated to ReSpec 2.1.10 for RM 2.1 PSD02:

image

**Comment by berezovskyi** [comment]
I think the PR should be merged because it works under latest ReSpec fairly well and other fixes can be made in subsequent PRs.

**Comment by jadelkhoury** [comment]
I guess I have to do the merge.

**Pull request merged**
