### PR TITLE
Add editor config file

### PR DESCRIPTION
**Pull request by berezovskyi**
I would like to begin enforcing some basic formatting rules for all files. Rationale:

1. Easy to read diffs. Following these rules will eliminate diffs with 100 lines removed and 100 added just because our editors have different indentation settings.
2. Easy to read diffs! Jim complained that long lines are impossible to compare in the web UI. **NB! Unfortunately, VS Code does not support `max_line_length`, you need to configure the editor.

### CODE REVIEW

**Comment by berezovskyi** [comment]
image

and

image

**Comment by ndjc** [comment]
Further to my previous comments: Eclipse Java IDE (one of the main downloads) does not support HTML formatting. Even if you add the Web plugins to get an HTML editor, as far as I can see there is no auto-wrapping at some maximum length - the editor has to remember to invoke an explicit format action, which to a large extent negates the line length aspect of this editorconfig proposal.

**Comment by berezovskyi** [comment]
Thanks Nick for taking a look at this!

1) Yes, that’s a problem. But I also don’t like when the editor formats things from under my feet, so to speak. Consequently, I invoke code formatter manually. I just want to make sure we agree on a number and try to enforce it as we see fit, so that Jim doesn’t say “too hard to review”. We can put it in CONTRIBUTING.md as an instruction. An alternative would be to install a pre-commit hook https://prettier.io/docs/en/precommit.html but that’s a pretty nuclear option.
2) Those settings affect the way your editor formats code. If you have your home settings, it can mess the formatting in a way that is not obvious. Compare to a gitignore in the home folder, which is pretty harmless in comparison. Feel free to add any settings you already have.
3) I fully agree.

--
/Andrew
(from phone)

13 aug. 2019 kl. 00:36 skrev Nick Crossley <notifications@github.com<mailto:notifications@github.com>>:


Further to my previous comments: Eclipse Java IDE (one of the main downloads) does not support HTML formatting. Even if you add the Web plugins to get an HTML editor, as far as I can see there is no auto-wrapping at some maximum length - the editor has to remember to invoke an explicit format action, which to a large extent negates the line length aspect of this editorconfig proposal.

**Comment by berezovskyi** [comment]
@nick I just updated the config wrt your wishes.

**Comment by nick** [comment]
hrm I don't remember making any suggestions 🤔

**Comment by berezovskyi** [comment]
oops, sorry @nick!

@ndjc please take a look :)

**Comment by berezovskyi** [comment]
I will also edit the CONTRIBUTING md file to request people either to install a plugin or set those settings by hand. Also, Atom is a common editor that supports all those settings with a plugin.

--
/Andrew
(from phone)

15 aug. 2019 kl. 18:54 skrev Nick Crossley <notifications@github.com<mailto:notifications@github.com>>:


@ndjc approved this pull request.

**Comment by berezovskyi** [comment]
@ndjc added README and a tab width config in case stray tabs will be found. Please merge if everything looks right.

**Pull request merged**
