### PR TITLE
Add a note about content precedence.

### LINKED ISSUE #120: Make a note of the spec/code precedence
Spec over code up until 2.0 incl.

Code over spec since 2.1/3.0.

### PR DESCRIPTION
**Pull request by berezovskyi**
We have this statement in the spec:

> Note that any machine-readable content (Computer Language Definitions) declared Normative for this Work Product is provided in separate plain text files. In the event of a discrepancy between any such plain text file and display content in the Work Product's prose narrative document(s), the content in the separate plain text file prevails.

But previous specs had different behaviour. Initially the discussed idea with Jim was to put both statements together in a normative section. In the process, I decided it would be better to keep the existing section normative in the header and add a new statement under an informative section (this PR).

Closes #120.

### CODE REVIEW

**Comment by jamsden** [comment]
The new specs should never have a discrepancy since the HTML is generated directly from the .ttl files.

**Comment by ndjc** [comment]
Typo in the new text - 'machine-readable'.

**Comment by berezovskyi** [comment]
> The new specs should never have a discrepancy since the HTML is generated directly from the .ttl files.

Well, once you say `oslc:range` in the Turtle to be X, I don't have to respect the description any more in the spec as the code text precedence :D

**Comment by berezovskyi** [comment]
Thanks @ndjc, fixed

**Comment by berezovskyi** [comment]
> The new specs should never have a discrepancy since the HTML is generated directly from the .ttl files.

Jim, the added non-normative statement spells out the change in the order of precedence between OSLC 2 and 3 specs explicitly.

**Pull request merged**
