### PR TITLE
Updates to publish OASIS Specification

### PR DESCRIPTION
**Pull request by jamsden**

### CODE REVIEW

**Comment by jamsden** [comment]
Looks like shape checker is not able to load http://xmlns.com/foaf/0.1/. Since there were not changes to the vocab or shapes other than boilerplate, I'm included to ignore this.

**Comment by berezovskyi** [comment]
Just merged latest changes from master to this branch

**Comment by berezovskyi** [comment]
https://docs.oasis-open-projects.org/oslc-op/config/v1.0/ps01/oslc-config-mgt-spec.html should be https://docs.oasis-open-projects.org/oslc-op/config/v1.0/ps01/oslc-config-mgt.html

**Review by berezovskyi — APPROVED** [review]
AM OS changes look fine to me.

**Pull request merged**
