### PR TITLE
Split the QM vocab

### LINKED ISSUE #355: QM Vocabulary uses undefined prefix oslc:
The QM vocabulary has added new properties oslc:inverseLabel, but the oslc prefix is not defined.

### LINKED ISSUE #368: Split QM vocab into vocab and shapes

### PR DESCRIPTION
**Pull request by berezovskyi**
Closes #368; also resolves #355

### CODE REVIEW

**Comment by berezovskyi** [comment]
@jamsden please review how the split was done

**Comment by berezovskyi** [comment]
@jamsden @ndjc I found more `com.ibm` references:

> 
> :TestResultShape
>   oslc:property        [ a                        oslc:Property ;
>                                oslc:allowedValue        "com.ibm.rqm.execution.common.state.failed" , "com.ibm.rqm.execution.common.state.inconclusive" , "com.ibm.rqm.execution.common.state.passed" , "com.ibm.rqm.execution.common.state.deferred" , "com.ibm.rqm.execution.common.state.incomplete" , "com.ibm.rqm.execution.common.state.blocked" , "com.ibm.rqm.execution.common.state.part_blocked" , "com.ibm.rqm.execution.common.state.perm_failed" , "com.ibm.rqm.execution.common.state.error" ;
>   oslc:name                "status" ;

What shall we do with it?

**Comment by berezovskyi** [comment]
@ndjc @jadelkhoury @DavidJHoney heads up on the slight changes in the part names introduced by Jim. I just matched what Jim did and suggest you do the same.

**Comment by jadelkhoury** [comment]
@berezovskyi I'll wait for the merge to master before I do to RM, to make sure I capture all changes.
I have already done the change suggested by @ndjc about conformance.

**Pull request merged**
