### PR TITLE
Prepare RM PS 02 for COS

### PR DESCRIPTION
**Pull request by berezovskyi**
- updated obsolete normative refs as per checklist
- updated respec version as per checklist
- made artifact URIs absolute as per checklist
- added conformance clauses in the Shapes part and the shapes files according to the ReSpec warnings.  ~🧨 #486 will have to be resolved till we can submit for COS~
- **Publication date is set for ~2021-03-01~ 2021-05-28**. ~Given that we notify the PGB of intent to publish (with a prepared ZIP next Friday, we will have 2 weeks for the review and then~ 1 week for a vote. _We assume the PGB has already voted on COS and knows about the COS revision process._
- updated copyright in RDF files to 2021 as per checklist
- updated meta tags to match abstract 1:1 as per checklist
- removed old files that were never published in OP

See #485

### CODE REVIEW

**Comment by berezovskyi** [comment]
@jamsden @jadelkhoury I added myself to the list of editors given that I was involved both in PSD and PS of it. Is it OK with you?

**Comment by jadelkhoury** [comment]
Fine by me.

**Comment by chet-ensign** [comment]
@berezovskyi - just making sure you know how we're handling public reviews now. You won't need to recreate a COS version of the PS. We add a public review metadata document to the PS and it stands for public review. Nothing on the doc needs to change until it is approved as an OASIS Standard.

**Comment by jamsden** [comment]
That's great Chet. We will still need to do a PS revision to pickup some final minor changes.

**Comment by berezovskyi** [comment]
Ah, interesting. Most of the changes you see here are the comments you and Paul left on RM PS01 and other specs. Do you want us then to release this as PS02 of the RM spec?

**Comment by chet-ensign** [comment]
No. If the changes came from us, then they are part of the publishing process. I don't want to make you have to go back and re-collect your Statements of Use.

**Comment by berezovskyi** [comment]
Ok! Thanks. What should be our next steps then? Would you pull changes you wish from here? Do we need to change or recall the notification to the PGB? I am not aware of the new process.

**Comment by chet-ensign** [comment]
Please remind me where things stand. You have your Statements of Use, correct? But I have not yet run a Special Majority Vote for the PGB to approve submitting the PS as a candidate for OASIS Standard? Right?

**Comment by berezovskyi** [comment]
That is correct.

**Comment by chet-ensign** [comment]
Ah and I see you opened a ticket for SMV so I'll get that queued up. 

From there it will be like normal. PGB approves the vote. We put out the word that the PS is out for public review with instructions on how to comment. You monitor and track as needed. At the end of the 60-days, I put it up for the call for consent.

**Comment by berezovskyi** [comment]
Thank you, Chet!

**Comment by berezovskyi** [comment]
PS02 was published, approved as OS. Merging to begin work on the OS.

**Pull request merged**
