### PR TITLE
Latest round of edits to the TRS draft

### PR DESCRIPTION
**Pull request by ndjc**
Ready for merge with master

### CODE REVIEW

**Comment by ndjc** [comment]
@berezovskyi  @DavidJHoney  @jamsden  - this PR for the TRS draft is still awaiting review.

**Review by berezovskyi — APPROVED** [review]
Comments inside. Normative statements will be reviewed once a get the PSD package and will be submitted against that PSD on the mailing list. Jim, please coordinate your changes to the draft for the PSD publication with Nick, I imagine you've already split the shapes and vocabs into different spec parts.

**Comment by jamsden** [comment]
I thought Nick was done, and started my own updates, including splitting out the shapes document. Too bad to waste the time. Let me know when its time for me to take the pen and I'll start over creating the PSD.

**Comment by berezovskyi** [comment]
@jamsden there are not so many changes I asked for. Maybe we can just agree that you will make them yourself and either update this PR or push a new one.

**Comment by ndjc** [comment]
I have NOT applied the changes suggested by @berezovskyi.

**Comment by berezovskyi** [comment]
OK, thanks. Jim, you can proceed with the package then without a need to start over.

**Pull request merged**
