### PR TITLE
Publish RM v2.1 PSD 02

### PR DESCRIPTION
**Pull request by berezovskyi**
Publication checklist:

- [x] base URI updated
- [x] `specStatus` updated
- [x] `publishDate` set
- [x] `latestVersion` updated to point to the one for the OP, not the TC (only for the first PSD)
- [x] open-services.net redirects resolve to the current published specs/drafts
- [x] `additionalArtifacts` links are relative
- [x] no broken links other than the stage-to-be-published
- [x] [release draft](https://github.com/oslc-op/oslc-specs/releases/tag/untagged-40b8102c05f3fa132447) created
- [x] [release zip](https://github.com/oslc-op/oslc-specs/releases/download/untagged-40b8102c05f3fa132447/rm-2.1-psd02_20190909.zip) uploaded
- [x] PGB vote initiated (Sep 10)
- [ ] PGB vote secured
- [x] OASIS review initiated (Sep 7)
- [ ] OASIS review passed
- [ ] OASIS archive uploaded
- [x] **OASIS:** in "Notices", the copyright year is missing - between "OASIS Open" and the period
- [x] **OASIS:** the links to the "Previous stage" should use http instead of https in this case, since the earlier files were installed with http links. When the HTML is retrieved using https, it is unable to load the associated .css file, so the document is poorly presented.
- [ ] **OASIS:** add HTTPS to the image references
- [x] **OASIS:** in Part 2: Vocabulary, I would expect that the first two definition blocks under Section 2.1.2 (Requirement and RequirementCollection) should be placed under 2.1.1, since they are Classes rather than Properties. See https://github.com/oasis-tcs/tab-respec/issues/17

After the publication:

- [ ] update the https://open-services.net/spec/rm/latest to point to https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/requirements-management-spec.html
- [ ] open-services.net blog announcement

### CODE REVIEW

**Comment by berezovskyi** [comment]
Link check:

image

**Comment by berezovskyi** [comment]
@jadelkhoury I just released ReSpec 2.1.11 that fixes the vocab grouping. Could you please update the specs to use the new JS file, fix the other comments from OASIS and publish the release HTML as a ZIP archive under the RM draft under https://github.com/oslc-op/oslc-specs/releases (and remove the old ZIP) and notify Paul and the OP list, please?

**Comment by jadelkhoury** [comment]
I pushed a new zip folder with the latest changes under https://github.com/oslc-op/oslc-specs/releases/tag/untagged-541eaa091109780b4623

But I got a respec error in the vocab html file: "A conformance paragraph or table is required for your type of document."!!! Did not quite get what this means.
But at least I have praticed how to do these steps.

> [x]  **OASIS:** in "Notices", the copyright year is missing - between "OASIS Open" and the period

    I changed respec version from 2.1.10 to 2.1.11.

> [x]  **OASIS:** the links to the "Previous stage" should use http instead of https in this case, ...

    I change the previousVersion" urls from https to http.

> []  **OASIS:** add HTTPS to the image references

? There are no images in this specs!

> [x]  **OASIS:** in Part 2: Vocabulary, I would expect that the first two definition blocks under Section 2.1.2 (Requirement and RequirementCollection) should be placed under 2.1.1, since they are Classes rather than Properties. See [oasis-tcs/tab-respec#17](https://github.com/oasis-tcs/tab-respec/issues/17)

Seems to be already done.

**Comment by berezovskyi** [comment]
@jadelkhoury it's fine, that warning is expected.

@OASIS-OP-Admin ready for final review.

**Comment by berezovskyi** [comment]
The version approved by the PGB merged, subsequent oasis feedback (if any) will be dealt separately.

**Comment by paul-knight** [comment]
Retrieved file https://github.com/oslc-op/oslc-specs/releases/download/untagged-541eaa091109780b4623/rm-2.1-psd02_20191003.zip.

Starting work for publication.

**Comment by paul-knight** [comment]
rm-2.1-psd02_20191003 comments

Overall, looks very good - links appear to be correct, and no format issues noted.

Part 1
- date is set as 09 September 2019 - probably should be 18 October (apparent PGB approval date)
- logo image does not appear in local view (i.e., using file:///) - due to use of link to "//docs.oasis-open-projects.org/templates/logo/open-projects-logo.png".
- Since I need for the image to be retrieved in local view in order to generate the PDF, I'll change this to begin with https:
- No other images noted.
- In Section 3, the link to Part 2: Vocabulary uses the hyperlink "http://docs.oasis-open.org/oslc-domains/oslc-rm/v2.1/oslc-rm-v2.1-part2-requirements-management-vocab.html". This will always point to the older (24 August 2018) cs01 stage. This should probably be replaced by a relative link to the current stage, using  ./requirements-management-vocab.html or possibly use the "Latest stage" link "https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/requirements-management-vocab.html".

Part 2
- same comments on date and logo image hyperlink.

**Comment by paul-knight** [comment]
Further work is being tracked in https://github.com/oasis-open-projects/administration/issues/7.

**Comment by berezovskyi** [comment]
Paul, is it possible to have you submit a pull request with the changes you’ve made? Or at least email us the diff with your changes? We’d like to prevent any divergence from the published docs in our repo. If you don’t have experience with Git but have time a can find a slot and do a hands on telco with you.

--
Andrew

________________________________
Från: Paul Knight <notifications@github.com>
Skickat: onsdag, oktober 23, 2019 4:44 em
Till: oslc-op/oslc-specs
Kopia: Andrew Berezovskyi; State change
Ämne: Re: [oslc-op/oslc-specs] Publish RM v2.1 PSD 02 (#230)


Further work is being tracked in oasis-open-projects/administration#7<https://github.com/oasis-open-projects/administration/issues/7>.

**Comment by paul-knight** [comment]
I just sent email with a couple of diff files (one per part).

**Pull request merged**
