### PR TITLE
QM WD fixes for PSD 02

### LINKED ISSUE #247: QM p.conformance paragraphs are not assigned c CC number
```html
<p class=‘conformance’>This specification is based on [[!OSLCCore3]]. OSLC QM
servers MUST be compliant with both the core specification,  MUST follow all
the mandatory requirements in the normative sections of this specification, and
SHOULD follow all the guidelines and recommendations in both these
specifications.</p>
```

image

### PR DESCRIPTION
**Pull request by berezovskyi**
This a PR to shape up the working draft. You will be able to review its rendered version once again after merging and there will be a separate PR to promote it to a PSD. 

NB! I did reformatting, you can review individual commits to be able to make sense of the PR.

Fixes #247

### CODE REVIEW

**Comment by ndjc** [comment]
In the localBiblio section, you've updated the URIs for OSLCCore3, OSLCPreview, OSLCCoreVocab, and OSLCShapes to point to the OASIS CSPRD03 on docs.oasis-open.org. That CSPRD is shortly to be replaced. Wouldn't the QM spec be better using a redirect for those references? I think we should have some links at open-services.net that can switch from the TC docs repo to the OP docs repo as required.

**Comment by ndjc** [comment]
Other than the above (and the back quotes or curly quotes for the p.conformance style, I'm OK with the changes.

**Comment by berezovskyi** [comment]
@ndjc when it comes to references, I would like them to point to the exact versions instead of redirects so that people who read the drafts can sanely inspect them and the references. when Core becomes a PSD, the references will be updated for the subsequent PSDs of all other specs.

**Comment by ndjc** [comment]
But what if for some reason QM becomes a PSD (or worse, a PS) before Core reaches the next PSD? In that case, it still seems wrong to me to point the QM spec reader to a CSPRD from the old TC - we would need to remember to change the references in QM before it became a PSD. What will force us to remember to do so?

**Pull request merged**
