### PR TITLE
Core: Use FQDN artif. links + update obsolete refs

### LINKED ISSUE #462: Part 8 §6 is missing conformance clause IDs
https://oslc-op.github.io/oslc-specs/specs/core/core-shapes.html#h2_conformance does not have a proper conformance clause table with XYZ-### identifiers.

This does not allow to label test failures like `org.eclipse.lyo.testsuite.oslcv2.ServiceProviderCatalogXmlTests#serviceProviderCatalogsHaveAtMostOneTitle` with a code, e.g. `CORSH-1` for the

> OSLC servers MUST follow the constraints defined here where required, and with the meanings defined here.

### PR DESCRIPTION
**Pull request by berezovskyi**
See #478 

Closes #462 

---

**TODOs**

- [x] remove `h2 class="normalText"`

### CODE REVIEW

**Comment by berezovskyi** [comment]
@jamsden summary:

- removed Part # from Machine Readable as requested by OASIS
- added a full URL to Additional Artifacts  as requested by OASIS
- updated "previous URLs"

**Comment by berezovskyi** [comment]
@jamsden I just updated all refs as long they were both: normative and obsolete. Please see outstanding issues with the references in tickets #482, #483, #484.

**Comment by berezovskyi** [comment]
@jamsden @ndjc initial fix for #462 is in the last commit [`966f6a9` (#481)](https://github.com/oslc-op/oslc-specs/pull/481/commits/966f6a9e167b82588cd2e654c3cf833b56ac16f4). Please check and I will then work through the rest of them.

**Comment by berezovskyi** [comment]
@jamsden @ndjc please review so that I can merge. This is not a mega-PR for PS 02. I am just pushing more stuff because I have not received a review and due to Pretty formatter it's not easy to work on parallel branches.

**Review by jamsden — CHANGES_REQUESTED** [review]
I didn't review every line, but I think this is ok. My recollection is that we agreed that conformance clauses wouldn't be used in the vocab and shapes because everything in those documents is required for conformance, and the content is largely already organized in convenient tables. I think this adds unnecessary clutter to these documents without adding much value. Consider reverting adding conformance tables to vocab and shape documents.

**Comment by berezovskyi** [comment]
Thanks Jim, I hold the same view (I did add a normative statement in the versioning section that machine-readable content takes precedence in 3.0) **but** the text from those files is rendered in the Part of a spec and people reading the Shapes Part (as opposed to actually studying the RDF definitions) need to be guided on how to interpret it. Those people won't have a crystal ball to say "oh, this stuff is generated from the Turtle files!". Also, some of our statements touch on what a range SHOULD be even though it MUST be at least an RDF resource. I think this kind of guidance deserves normative statements. Otherwise, I will be fine if that language is removed from the tables altogether (but I guess we want to keep it). I will not add more normative statements to the Turtle files and maybe stash & revert them to merge before Thursday, and we should discuss it then.

**Review by ndjc — COMMENTED** [review]
I've added a commit that fixes more of the conformance issues in the spec and the shapes.

For the vocabulary, I agree with Jim that vocabulary should not need conformance clauses; the format of those documents is a W3C standard. I've avoided the issue by recording the vocabulary to avoid RFC 2119 terms - review the result and let me know what you both think.

With these changes, ReSpec has no conformance clause warnings on core-shapes.html.

**Comment by ndjc** [comment]
I think having conformance clauses in shapes is desirable; the Config Management spec is full of them. Don't forget that ReSpec has an easy way to mark such conformance clauses using {{...text...}}; I updated core-shapes.ttl to use that technique.

**Comment by jamsden** [comment]
I think it just adds redundancy to the specs.

**Comment by berezovskyi** [comment]
Merging the WD so that you can perform review of an HTML WD. Shapes CC objection was resolved during the call today.

**Comment by berezovskyi** [comment]
Shapecheck errors are due to commenting out the properties added during release.

**Pull request merged**
