### PR TITLE
Switch from Ant to Gradle

### PR DESCRIPTION
**Pull request by berezovskyi**

### CODE REVIEW

**Comment by berezovskyi** [comment]
@chet-ensign @OASIS-OP-Admin shouldn't I be whitelisted for the CLA here?

**Comment by berezovskyi** [comment]
@ndjc the build now seems to work but the return code of the checker seems to be always 0 and it does not fail the build: https://circleci.com/gh/oslc-op/oslc-specs/38

I would like to call `System.exit(1)` at the end of the check if there is at least one error.

**Comment by berezovskyi** [comment]
@ndjc, I just made a small change and the tests now fail as they should: https://circleci.com/gh/oslc-op/oslc-specs/39

**Comment by berezovskyi** [comment]
1) Yes but I would like to get rid of the JARs in the lib folder. We can begin at least ignoring the ShapeChecker jar first. Could you also please update the build.xml? I can't get it to produce working JARs on my machine even before the change in the layout.
2) Yes, I opened another issue for that.
3) Hmm, let me look at that tomorrow.

Thanks!

--
/Andrew
(from phone)



On Wed, May 29, 2019 at 11:10 PM +0200, "Nick Crossley" <notifications@github.com<mailto:notifications@github.com>> wrote:


@ndjc commented on this pull request.

  1.  Could we keep an updated build.xml so my Ant builds work with the revised source structure? I do not have Gradle set up at all on my systems yet.
  2.  Some 'errors' are very minor, and not easily avoided with the architectural issue we discussed, so be aware of that when you use the new exit status you return.
  3.  These changes will require some corresponding changes to the newly-added ShapeChecker annotation processor under tools/scapt.

**Comment by ndjc** [comment]
I merged your change, and then added back a working Ant build.xml. That build.xml relies on the previous lib directory holding all the dependencies, so I just marked that as ignored and have it as local in my working tree until I find some way to move to Gradle or whatever.

**Pull request merged**
