### PR TITLE
Add ABNF grammar and a conf clause

### LINKED ISSUE #459: Register OSLC-Core-Version header with IANA
Filed in connection with #458. I don't think we shall wait #144, Core spec is more mature and will allow us to get a faster allocation.

**TODOs:**

- [x] Read https://tools.ietf.org/html/rfc7231#section-8.3
- [x] Check https://www.iana.org/assignments/message-headers/message-headers.xhtml
- [x] Define ABNF syntax
- [x] Check off every Whether consideration
- [x] Follow https://tools.ietf.org/html/bcp90#section-4
- [x] Submit an registration request to IETF as is without waiting for #475 or #476 (**2020-02-06**)
- [x] Wait 2 weeks and submit an application to IANA if no objections are received on https://mailarchive.ietf.org/arch/browse/ietf-message-headers/# (sched. **2020-02-22**; +https://tools.ietf.org/html/bcp90#section-4.3)

### PR DESCRIPTION
**Pull request by berezovskyi**
**TODOs**

- [ ] ~Bring in the versioning requirements from the old spec as agreed in https://github.com/oslc-op/oslc-admin/blob/master/minutes/2021/2021-02-04.md#iana-application~ Will deal with #475 and #476 in a separate MR
- [ ] Make section normative
- [ ] Remove TODO
- [ ] Prettier downgrade

---

See #459

### CODE REVIEW

**Review by ndjc — CHANGES_REQUESTED** [review]
The new text has a TODO comment - surely this must be resolved before merging with master?

**Comment by berezovskyi** [comment]
@ndjc I think I will change the action from what we agreed in the call. I will remove the TODO (and switch it to normative, perhaps, see below) and merge this PR first so that the IANA submission can look at the https://oslc-op.github.io/oslc-specs/specs/core/oslc-core.html#versionCompatibility when they check our submission (though I can predict they won't like the non-normative notice). And once that lands on master, I will start working on overhauling the whole section.

**Comment by berezovskyi** [comment]
@ndjc ready for review (touches on #475, sorry I could not stop after seeing and fixing a few lowercase may's and should's), I will email IETF and begin work on #476 and finish #475.

**Comment by berezovskyi** [comment]
Using my co-chair superpowers to merge it into the draft, PRs/requests to undo parts of it later are welcome

**Pull request merged**
